name: Build C C++ Java

on:
  push:
  pull_request:

jobs:
  c:
    name: Build C
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile C
        run: gcc pattern.c -o pattern-c

      - name: Run C
        run: ./pattern-c

  cpp:
    name: Build C++
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile C++
        run: g++ circle.cpp -o circle-cpp

      - name: Run C++
        run: ./circle-cpp

  java:
    name: Build Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Java
        run: javac Demo.java

      - name: Run Java
        run: java Demo
